/* Contains IDs used by the Torn API that are not available from an endpoint.
	Must be parsed after the main file.
	Keys should be lowercase and singular, sorted alphabetically.
	Null any missing entries to maintain sequence; double quote all strings.
*/
window.TornAPIReader.logIDs.torn = {
	/* id: [description, category, (sub-category)] */
	crime: {
		1: ["Search the Train Station", "Search for Cash"],
		2: ["Search Under the Old Bridge", "Search for Cash"],
		3: ["Search the Bins", "Search for Cash"],
		4: ["Search the Water Fountain", "Search for Cash"],
		5: ["Search the Dumpsters", "Search for Cash"],
		6: ["Search the Movie Theater", "Search for Cash"],
		7: ["Rock CDs", "Sell Copied Media"],
		8: ["Heavy Metal CDs", "Sell Copied Media"],
		9: ["Pop CDs", "Sell Copied Media"],
		10: ["Rap CDs", "Sell Copied Media"],
		11: ["Reggae CDs", "Sell Copied Media"],
		12: ["Horror DVDs", "Sell Copied Media"],
		13: ["Action DVDs", "Sell Copied Media"],
		14: ["Romance DVDs", "Sell Copied Media"],
		15: ["Sci Fi DVDs", "Sell Copied Media"],
		16: ["Thriller DVDs", "Sell Copied Media"],
		17: ["A Few Chocolate Bars", "Shoplift", "Sweet Shop"],
		18: ["A Few Bags of Bonbons", "Shoplift", "Sweet Shop"],
		19: ["A Box of Extra Strong Mints", "Shoplift", "Sweet Shop"],
		20: ["Music Stall", "Shoplift", "Market Stall"],
		21: ["Electronics Stall", "Shoplift", "Market Stall"],
		22: ["Computer Stall", "Shoplift", "Market Stall"],
		23: ["Tank Top", "Shoplift", "Clothes Shop"],
		24: ["Trainers", "Shoplift", "Clothes Shop"],
		25: ["Jacket", "Shoplift", "Clothes Shop"],
		26: ["Watch", "Shoplift", "Jewelry Shop"],
		27: ["Necklace", "Shoplift", "Jewelry Shop"],
		28: ["Ring", "Shoplift", "Jewelry Shop"],
		29: ["Hobo", "Pickpocket Someone"],
		30: ["Kid", "Pickpocket Someone"],
		31: ["Old Woman", "Pickpocket Someone"],
		32: ["Businessman", "Pickpocket Someone"],
		33: ["Lawyer", "Pickpocket Someone"],
		34: ["Apartment", "Larceny"],
		35: ["Detached House", "Larceny"],
		36: ["Mansion", "Larceny"],
		37: ["Cars", "Larceny"],
		38: ["Office", "Larceny"],
		39: ["Swift Robbery", "Armed Robberies"],
		40: ["Thorough Robbery", "Armed Robberies"],
		41: ["Swift Convenience", "Armed Robberies"],
		42: ["Thorough Convenience", "Armed Robberies"],
		43: ["Swift Bank", "Armed Robberies"],
		44: ["Thorough Bank", "Armed Robberies"],
		45: ["Swift Armored Car", "Armed Robberies"],
		46: ["Thorough Armored Car", "Armed Robberies"],
		47: ["Transport Cannabis", "Transport Drugs"],
		48: ["Transport Amphetamines", "Transport Drugs"],
		49: ["Transport Cocaine", "Transport Drugs"],
		50: ["Sell Cannabis", "Transport Drugs"],
		51: ["Sell Pills", "Transport Drugs"],
		52: ["Sell Cocaine", "Transport Drugs"],
		53: ["Simple Virus", "Plant a Computer Virus"],
		54: ["Polymorphic Virus", "Plant a Computer Virus"],
		55: ["Tunneling Virus", "Plant a Computer Virus"],
		56: ["Armored Virus", "Plant a Computer Virus"],
		57: ["Stealth Virus", "Plant a Computer Virus"],
		58: ["Assassinate a Target", "Assassination"],
		59: ["Drive-by Shooting", "Assassination"],
		60: ["Car Bomb", "Assassination"],
		61: ["Mob Boss", "Assassination"],
		62: ["Home", "Arson"],
		63: ["Car Lot", "Arson"],
		64: ["Office Building", "Arson"],
		65: ["Apartment Building", "Arson"],
		66: ["Warehouse", "Arson"],
		67: ["Motel", "Arson"],
		68: ["Government Building", "Arson"],
		69: ["Steal a Parked Car", "Grand Theft Auto"],
		70: ["Hijack a Car", "Grand Theft Auto"],
		71: ["Steal Car from Showroom", "Grand Theft Auto"],
		72: ["Side Door", "Pawn Shop"],
		73: ["Rear Door", "Pawn Shop"],
		74: ["Money", "Counterfeiting"],
		75: ["Casino Tokens", "Counterfeiting"],
		76: ["Credit Card", "Counterfeiting"],
		77: ["Kid", "Kidnapping"],
		78: ["Woman", "Kidnapping"],
		79: ["Undercover Cop", "Kidnapping"],
		80: ["Mayor", "Kidnapping"],
		81: ["Explosives", "Arms Trafficking"],
		82: ["Firearms", "Arms Trafficking"],
		83: ["Bomb a Factory", "Bombings"],
		84: ["Bomb a Government Building", "Bombings"],
		85: ["Hack into a Bank Mainframe", "Hacking"],
		86: ["Hack the F.B.I. Mainframe", "Hacking"],// corrected punctuation
	},
	/* id: name */
	gymstage: {
		0: "Other",
		1: "Lightweight",
		2: "Middleweight",
		3: "Heavyweight",
		4: "Specialist",
	},
	/* id: name */
	racetrack: {
		1: null,
		2: null,
		3: null,
		4: null,
		5: null,
		6: "Uptown",
		7: "Withdrawal",
		8: "Underdog",
		9: "Parkland",
		10: "Docks",
		11: "Commerce",
		12: "Two Islands",
		13: null,
		14: null,
		15: "Industrial",
		16: "Vector",
		17: "Mudpit",
		18: "Hammerhead",
		19: "Sewage",
		20: "Meltdown",
		21: "Speedway",
		22: null,
		23: "Stone Park",
		24: "Convict",
	},
};